name: ci

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: php bin/phpunit --coverage-clover=clover.xml
